export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const DONATION = "DONATION";
export const DONATION_LOADING = "DONATION_LOADING";
export const DONATION_SUCCESS = "DONATION_SUCCESS";
export const DONATION_ERROR = "DONATION_ERROR";

export const UPLOAD_DONATION = "UPLOAD_DONATION";
export const UPLOAD_DONATION_LOADING = "UPLOAD_DONATION_LOADING";
export const UPLOAD_DONATION_SUCCESS = "UPLOAD_DONATION_SUCCESS";
export const UPLOAD_DONATION_ERROR = "UPLOAD_DONATION_ERROR";