export const FundraiserCardData = [
  {
    cardimg: "/img/fundraiser1.png",
    location: "Nepal",
    title: "Bibek Ghimire",
    desc: "Hats off to all the volunteers doing such great work in this pandemic situation. ",
    lastDonated: "4 days ago",
    gainedDonation: "$1000 ",
    donationLevel: "Top Donation",
  },
  {
    cardimg: "/img/fundraiser2.png",
    location: "Nepal",
    title: "Pasang Sherpa",
    desc: "Thank you so much to the HamiNepal team for all that you are doing. ",
    lastDonated: "3 days ago",
    gainedDonation: "$400 ",
    donationLevel: "Recent Donation",
  },
  {
    cardimg: "https://image.flaticon.com/icons/png/512/3135/3135715.png",
    location: "Nepal",
    title: "Nepali Events",
    desc: "Thank you so much to the HamiNepal team for all that you are doing. ",
    lastDonated: "1 days ago",
    gainedDonation: "$1001 ",
    donationLevel: "Recent Donation",
  },
  {
    cardimg: "https://image.flaticon.com/icons/png/512/3135/3135715.png",
    location: "AUS",
    title: "Anonymous",
    desc: "Thank you so much to the HamiNepal team for all that you are doing. ",
    lastDonated: "2 days ago",
    gainedDonation: "$20 ",
    donationLevel: "Recent Donation",
  },
  {
    cardimg: "https://image.flaticon.com/icons/png/512/3135/3135715.png",
    location: "Nepal",
    title: "Laxmi Goudel",
    desc: "Thank you so much to the HamiNepal team for all that you are doing. ",
    lastDonated: "2 days ago",
    gainedDonation: "$50",
    donationLevel: "Recent Donation",
  },
  {
    cardimg: "https://image.flaticon.com/icons/png/512/3135/3135715.png",
    location: "Nepal",
    title: "Tenzing Lama",
    desc: "Thank you so much to the HamiNepal team for all that you are doing. ",
    lastDonated: "3 days ago",
    gainedDonation: "$100",
    donationLevel: "Recent Donation",
  },
  {
    cardimg: "https://image.flaticon.com/icons/png/512/3135/3135715.png",
    location: "USA",
    title: "Rina Chhantyal",
    desc: "Thank you so much to the HamiNepal team for all that you are doing. ",
    lastDonated: "1 days ago",
    gainedDonation: "$1001 ",
    donationLevel: "Recent Donation",
  },
  {
    cardimg: "https://image.flaticon.com/icons/png/512/3135/3135715.png",
    location: "AUS",
    title: "Harrison Miller",
    desc: "Thank you so much to the HamiNepal team for all that you are doing. ",
    lastDonated: "3 days ago",
    gainedDonation: "$50 ",
    donationLevel: "Recent Donation",
  },
  {
    cardimg: "https://image.flaticon.com/icons/png/512/3135/3135715.png",
    location: "Nepal",
    title: "Nischal Shakya",
    desc: "Thank you so much to the HamiNepal team for all that you are doing. ",
    lastDonated: "4 days ago",
    gainedDonation: "$10",
    donationLevel: "Recent Donation",
  },
  {
    cardimg: "https://image.flaticon.com/icons/png/512/3135/3135715.png",
    location: "Nepal",
    title: "Shibani Pradhan",
    desc: "Thank you so much to the HamiNepal team for all that you are doing. ",
    lastDonated: "4 days ago",
    gainedDonation: "$100",
    donationLevel: "Recent Donation",
  },
  {
    cardimg: "https://image.flaticon.com/icons/png/512/3135/3135715.png",
    location: "UK",
    title: "Roshan Thapa",
    desc: "Thank you so much to the HamiNepal team for all that you are doing. ",
    lastDonated: "4 days ago",
    gainedDonation: "$50",
    donationLevel: "Recent Donation",
  },
  {
    cardimg: "https://image.flaticon.com/icons/png/512/3135/3135715.png",
    location: "Nepal",
    title: "Shreya Rai ",
    desc: "Thank you so much to the HamiNepal team for all that you are doing. ",
    lastDonated: "6 days ago",
    gainedDonation: "$15",
    donationLevel: "Recent Donation",
  },
  {
    cardimg: "https://image.flaticon.com/icons/png/512/3135/3135715.png",
    location: "USA",
    title: "Catherine Cotonat",
    desc: "Thank you so much to the HamiNepal team for all that you are doing. ",
    lastDonated: "6 days ago",
    gainedDonation: "$1001 ",
    donationLevel: "Recent Donation",
  },
  {
    cardimg: "https://image.flaticon.com/icons/png/512/3135/3135715.png",
    location: "USA",
    title: "Ivo van Delden",
    desc: "Thank you so much to the HamiNepal team for all that you are doing. ",
    lastDonated: "9 days ago",
    gainedDonation: "$1100 ",
    donationLevel: "Recent Donation",
  },
];
